CURRENCIES = [
    {"code": "AED", "name": "UAE Dirham", "symbol": "د.إ", "numericCode": "784", "country": "United Arab Emirates"},
    {"code": "AFN", "name": "Afghan Afghani", "symbol": "؋", "numericCode": "971", "country": "Afghanistan"},
    {"code": "ALL", "name": "Albanian Lek", "symbol": "L", "numericCode": "008", "country": "Albania"},
    {"code": "AMD", "name": "Armenian Dram", "symbol": "֏", "numericCode": "051", "country": "Armenia"},
    {"code": "ANG", "name": "Netherlands Antillean Guilder", "symbol": "ƒ", "numericCode": "532", "country": ["Curaçao", "Sint Maarten"]},
    {"code": "AOA", "name": "Angolan Kwanza", "symbol": "Kz", "numericCode": "973", "country": "Angola"},
    {"code": "ARS", "name": "Argentine Peso", "symbol": "$", "numericCode": "032", "country": "Argentina"},
    {"code": "AUD", "name": "Australian Dollar", "symbol": "$", "numericCode": "036", "country": "Australia"},
    {"code": "AWG", "name": "Aruban Florin", "symbol": "ƒ", "numericCode": "533", "country": "Aruba"},
    {"code": "AZN", "name": "Azerbaijani Manat", "symbol": "₼", "numericCode": "944", "country": "Azerbaijan"},
    {"code": "BAM", "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "KM", "numericCode": "977", "country": "Bosnia and Herzegovina"},
    {"code": "BBD", "name": "Barbadian Dollar", "symbol": "$", "numericCode": "052", "country": "Barbados"},
    {"code": "BDT", "name": "Bangladeshi Taka", "symbol": "৳", "numericCode": "050", "country": "Bangladesh"},
    {"code": "BGN", "name": "Bulgarian Lev", "symbol": "лв", "numericCode": "975", "country": "Bulgaria"},
    {"code": "BHD", "name": "Bahraini Dinar", "symbol": ".د.ب", "numericCode": "048", "country": "Bahrain"},
    {"code": "BIF", "name": "Burundian Franc", "symbol": "FBu", "numericCode": "108", "country": "Burundi"},
    {"code": "BMD", "name": "Bermudian Dollar", "symbol": "$", "numericCode": "060", "country": "Bermuda"},
    {"code": "BND", "name": "Brunei Dollar", "symbol": "$", "numericCode": "096", "country": "Brunei"},
    {"code": "BOB", "name": "Bolivian Boliviano", "symbol": "Bs.", "numericCode": "068", "country": "Bolivia"},
    {"code": "BRL", "name": "Brazilian Real", "symbol": "R$", "numericCode": "986", "country": "Brazil"},
    {"code": "BSD", "name": "Bahamian Dollar", "symbol": "$", "numericCode": "044", "country": "Bahamas"},
    {"code": "BTN", "name": "Bhutanese Ngultrum", "symbol": "Nu.", "numericCode": "064", "country": "Bhutan"},
    {"code": "BWP", "name": "Botswana Pula", "symbol": "P", "numericCode": "072", "country": "Botswana"},
    {"code": "BYN", "name": "Belarusian Ruble", "symbol": "Br", "numericCode": "933", "country": "Belarus"},
    {"code": "BZD", "name": "Belize Dollar", "symbol": "BZ$", "numericCode": "084", "country": "Belize"},
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "$", "numericCode": "124", "country": "Canada"},
    {"code": "CDF", "name": "Congolese Franc", "symbol": "FC", "numericCode": "976", "country": "DR Congo"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF", "numericCode": "756", "country": "Switzerland"},
    {"code": "CLP", "name": "Chilean Peso", "symbol": "$", "numericCode": "152", "country": "Chile"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥", "numericCode": "156", "country": "China"},
    {"code": "COP", "name": "Colombian Peso", "symbol": "$", "numericCode": "170", "country": "Colombia"},
    {"code": "CRC", "name": "Costa Rican Colón", "symbol": "₡", "numericCode": "188", "country": "Costa Rica"},
    {"code": "CUP", "name": "Cuban Peso", "symbol": "$", "numericCode": "192", "country": "Cuba"},
    {"code": "CVE", "name": "Cape Verdean Escudo", "symbol": "$", "numericCode": "132", "country": "Cabo Verde"},
    {"code": "CZK", "name": "Czech Koruna", "symbol": "Kč", "numericCode": "203", "country": "Czech Republic"},
    {"code": "DJF", "name": "Djiboutian Franc", "symbol": "Fdj", "numericCode": "262", "country": "Djibouti"},
    {"code": "DKK", "name": "Danish Krone", "symbol": "kr", "numericCode": "208", "country": "Denmark"},
    {"code": "DOP", "name": "Dominican Peso", "symbol": "RD$", "numericCode": "214", "country": "Dominican Republic"},
    {"code": "DZD", "name": "Algerian Dinar", "symbol": "دج", "numericCode": "012", "country": "Algeria"},
    {"code": "EGP", "name": "Egyptian Pound", "symbol": "£", "numericCode": "818", "country": "Egypt"},
    {"code": "ERN", "name": "Eritrean Nakfa", "symbol": "Nfk", "numericCode": "232", "country": "Eritrea"},
    {"code": "ETB", "name": "Ethiopian Birr", "symbol": "Br", "numericCode": "230", "country": "Ethiopia"},
    {
        "code": "EUR",
        "name": "Euro",
        "symbol": "€",
        "numericCode": "978",
        "country": [
            "Germany", "France", "Italy", "Spain", "Netherlands", "Belgium",
            "Austria", "Ireland", "Portugal", "Greece", "Finland", "Slovakia",
            "Slovenia", "Luxembourg", "Latvia", "Lithuania", "Estonia",
            "Cyprus", "Malta", "Croatia",
        ],
    },
    {"code": "FJD", "name": "Fijian Dollar", "symbol": "$", "numericCode": "242", "country": "Fiji"},
    {"code": "FKP", "name": "Falkland Islands Pound", "symbol": "£", "numericCode": "238", "country": "Falkland Islands"},
    {"code": "GBP", "name": "British Pound", "symbol": "£", "numericCode": "826", "country": "United Kingdom"},
    {"code": "GEL", "name": "Georgian Lari", "symbol": "₾", "numericCode": "981", "country": "Georgia"},
    {"code": "GHS", "name": "Ghanaian Cedi", "symbol": "₵", "numericCode": "936", "country": "Ghana"},
    {"code": "GIP", "name": "Gibraltar Pound", "symbol": "£", "numericCode": "292", "country": "Gibraltar"},
    {"code": "GMD", "name": "Gambian Dalasi", "symbol": "D", "numericCode": "270", "country": "Gambia"},
    {"code": "GNF", "name": "Guinean Franc", "symbol": "FG", "numericCode": "324", "country": "Guinea"},
    {"code": "GTQ", "name": "Guatemalan Quetzal", "symbol": "Q", "numericCode": "320", "country": "Guatemala"},
    {"code": "GYD", "name": "Guyanese Dollar", "symbol": "$", "numericCode": "328", "country": "Guyana"},
    {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "$", "numericCode": "344", "country": "Hong Kong"},
    {"code": "HNL", "name": "Honduran Lempira", "symbol": "L", "numericCode": "340", "country": "Honduras"},
    {"code": "HTG", "name": "Haitian Gourde", "symbol": "G", "numericCode": "332", "country": "Haiti"},
    {"code": "HUF", "name": "Hungarian Forint", "symbol": "Ft", "numericCode": "348", "country": "Hungary"},
    {"code": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp", "numericCode": "360", "country": "Indonesia"},
    {"code": "ILS", "name": "Israeli New Shekel", "symbol": "₪", "numericCode": "376", "country": "Israel"},
    {"code": "INR", "name": "Indian Rupee", "symbol": "₹", "numericCode": "356", "country": "India"},
    {"code": "IQD", "name": "Iraqi Dinar", "symbol": "ع.د", "numericCode": "368", "country": "Iraq"},
    {"code": "IRR", "name": "Iranian Rial", "symbol": "﷼", "numericCode": "364", "country": "Iran"},
    {"code": "ISK", "name": "Icelandic Króna", "symbol": "kr", "numericCode": "352", "country": "Iceland"},
    {"code": "JMD", "name": "Jamaican Dollar", "symbol": "$", "numericCode": "388", "country": "Jamaica"},
    {"code": "JOD", "name": "Jordanian Dinar", "symbol": "د.ا", "numericCode": "400", "country": "Jordan"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥", "numericCode": "392", "country": "Japan"},
    {"code": "KES", "name": "Kenyan Shilling", "symbol": "KSh", "numericCode": "404", "country": "Kenya"},
    {"code": "KGS", "name": "Kyrgyzstani Som", "symbol": "лв", "numericCode": "417", "country": "Kyrgyzstan"},
    {"code": "KHR", "name": "Cambodian Riel", "symbol": "៛", "numericCode": "116", "country": "Cambodia"},
    {"code": "KMF", "name": "Comorian Franc", "symbol": "CF", "numericCode": "174", "country": "Comoros"},
    {"code": "KPW", "name": "North Korean Won", "symbol": "₩", "numericCode": "408", "country": "North Korea"},
    {"code": "KRW", "name": "South Korean Won", "symbol": "₩", "numericCode": "410", "country": "South Korea"},
    {"code": "KWD", "name": "Kuwaiti Dinar", "symbol": "د.ك", "numericCode": "414", "country": "Kuwait"},
    {"code": "KYD", "name": "Cayman Islands Dollar", "symbol": "$", "numericCode": "136", "country": "Cayman Islands"},
    {"code": "KZT", "name": "Kazakhstani Tenge", "symbol": "₸", "numericCode": "398", "country": "Kazakhstan"},
    {"code": "LAK", "name": "Lao Kip", "symbol": "₭", "numericCode": "418", "country": "Laos"},
    {"code": "LBP", "name": "Lebanese Pound", "symbol": "ل.ل", "numericCode": "422", "country": "Lebanon"},
    {"code": "LKR", "name": "Sri Lankan Rupee", "symbol": "₨", "numericCode": "144", "country": "Sri Lanka"},
    {"code": "LRD", "name": "Liberian Dollar", "symbol": "$", "numericCode": "430", "country": "Liberia"},
    {"code": "LSL", "name": "Lesotho Loti", "symbol": "L", "numericCode": "426", "country": "Lesotho"},
    {"code": "LYD", "name": "Libyan Dinar", "symbol": "ل.د", "numericCode": "434", "country": "Libya"},
    {"code": "MAD", "name": "Moroccan Dirham", "symbol": "د.م.", "numericCode": "504", "country": "Morocco"},
    {"code": "MDL", "name": "Moldovan Leu", "symbol": "L", "numericCode": "498", "country": "Moldova"},
    {"code": "MGA", "name": "Malagasy Ariary", "symbol": "Ar", "numericCode": "969", "country": "Madagascar"},
    {"code": "MKD", "name": "Macedonian Denar", "symbol": "ден", "numericCode": "807", "country": "North Macedonia"},
    {"code": "MMK", "name": "Myanmar Kyat", "symbol": "K", "numericCode": "104", "country": "Myanmar"},
    {"code": "MNT", "name": "Mongolian Tögrög", "symbol": "₮", "numericCode": "496", "country": "Mongolia"},
    {"code": "MOP", "name": "Macanese Pataca", "symbol": "MOP$", "numericCode": "446", "country": "Macau"},
    {"code": "MRU", "name": "Mauritanian Ouguiya", "symbol": "UM", "numericCode": "929", "country": "Mauritania"},
    {"code": "MUR", "name": "Mauritian Rupee", "symbol": "₨", "numericCode": "480", "country": "Mauritius"},
    {"code": "MVR", "name": "Maldivian Rufiyaa", "symbol": ".ރ", "numericCode": "462", "country": "Maldives"},
    {"code": "MWK", "name": "Malawian Kwacha", "symbol": "MK", "numericCode": "454", "country": "Malawi"},
    {"code": "MXN", "name": "Mexican Peso", "symbol": "$", "numericCode": "484", "country": "Mexico"},
    {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM", "numericCode": "458", "country": "Malaysia"},
    {"code": "MZN", "name": "Mozambican Metical", "symbol": "MT", "numericCode": "943", "country": "Mozambique"},
    {"code": "NAD", "name": "Namibian Dollar", "symbol": "$", "numericCode": "516", "country": "Namibia"},
    {"code": "NGN", "name": "Nigerian Naira", "symbol": "₦", "numericCode": "566", "country": "Nigeria"},
    {"code": "NIO", "name": "Nicaraguan Córdoba", "symbol": "C$", "numericCode": "558", "country": "Nicaragua"},
    {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr", "numericCode": "578", "country": "Norway"},
    {"code": "NPR", "name": "Nepalese Rupee", "symbol": "₨", "numericCode": "524", "country": "Nepal"},
    {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$", "numericCode": "554", "country": "New Zealand"},
    {"code": "OMR", "name": "Omani Rial", "symbol": "﷼", "numericCode": "512", "country": "Oman"},
    {"code": "PAB", "name": "Panamanian Balboa", "symbol": "B/.", "numericCode": "590", "country": "Panama"},
    {"code": "PEN", "name": "Peruvian Sol", "symbol": "S/", "numericCode": "604", "country": "Peru"},
    {"code": "PGK", "name": "Papua New Guinean Kina", "symbol": "K", "numericCode": "598", "country": "Papua New Guinea"},
    {"code": "PHP", "name": "Philippine Peso", "symbol": "₱", "numericCode": "608", "country": "Philippines"},
    {"code": "PKR", "name": "Pakistani Rupee", "symbol": "₨", "numericCode": "586", "country": "Pakistan"},
    {"code": "PLN", "name": "Polish Złoty", "symbol": "zł", "numericCode": "985", "country": "Poland"},
    {"code": "PYG", "name": "Paraguayan Guaraní", "symbol": "₲", "numericCode": "600", "country": "Paraguay"},
    {"code": "QAR", "name": "Qatari Riyal", "symbol": "﷼", "numericCode": "634", "country": "Qatar"},
    {"code": "RON", "name": "Romanian Leu", "symbol": "lei", "numericCode": "946", "country": "Romania"},
    {"code": "RSD", "name": "Serbian Dinar", "symbol": "дин.", "numericCode": "941", "country": "Serbia"},
    {"code": "RUB", "name": "Russian Ruble", "symbol": "₽", "numericCode": "643", "country": "Russia"},
    {"code": "RWF", "name": "Rwandan Franc", "symbol": "FRw", "numericCode": "646", "country": "Rwanda"},
    {"code": "SAR", "name": "Saudi Riyal", "symbol": "﷼", "numericCode": "682", "country": "Saudi Arabia"},
    {"code": "SBD", "name": "Solomon Islands Dollar", "symbol": "$", "numericCode": "090", "country": "Solomon Islands"},
    {"code": "SCR", "name": "Seychellois Rupee", "symbol": "₨", "numericCode": "690", "country": "Seychelles"},
    {"code": "SDG", "name": "Sudanese Pound", "symbol": "ج.س.", "numericCode": "938", "country": "Sudan"},
    {"code": "SEK", "name": "Swedish Krona", "symbol": "kr", "numericCode": "752", "country": "Sweden"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "$", "numericCode": "702", "country": "Singapore"},
    {"code": "SHP", "name": "Saint Helena Pound", "symbol": "£", "numericCode": "654", "country": "Saint Helena"},
    {"code": "SLE", "name": "Sierra Leonean Leone", "symbol": "Le", "numericCode": "925", "country": "Sierra Leone"},
    {"code": "SOS", "name": "Somali Shilling", "symbol": "S", "numericCode": "706", "country": "Somalia"},
    {"code": "SRD", "name": "Surinamese Dollar", "symbol": "$", "numericCode": "968", "country": "Suriname"},
    {"code": "SSP", "name": "South Sudanese Pound", "symbol": "£", "numericCode": "728", "country": "South Sudan"},
    {"code": "STN", "name": "São Tomé and Príncipe Dobra", "symbol": "Db", "numericCode": "930", "country": "São Tomé and Príncipe"},
    {"code": "SYP", "name": "Syrian Pound", "symbol": "£", "numericCode": "760", "country": "Syria"},
    {"code": "SZL", "name": "Eswatini Lilangeni", "symbol": "L", "numericCode": "748", "country": "Eswatini"},
    {"code": "THB", "name": "Thai Baht", "symbol": "฿", "numericCode": "764", "country": "Thailand"},
    {"code": "TJS", "name": "Tajikistani Somoni", "symbol": "ЅМ", "numericCode": "972", "country": "Tajikistan"},
    {"code": "TMT", "name": "Turkmenistani Manat", "symbol": "m", "numericCode": "934", "country": "Turkmenistan"},
    {"code": "TND", "name": "Tunisian Dinar", "symbol": "د.ت", "numericCode": "788", "country": "Tunisia"},
    {"code": "TOP", "name": "Tongan Paʻanga", "symbol": "T$", "numericCode": "776", "country": "Tonga"},
    {"code": "TRY", "name": "Turkish Lira", "symbol": "₺", "numericCode": "949", "country": "Turkey"},
    {"code": "TTD", "name": "Trinidad and Tobago Dollar", "symbol": "$", "numericCode": "780", "country": "Trinidad and Tobago"},
    {"code": "TWD", "name": "New Taiwan Dollar", "symbol": "$", "numericCode": "901", "country": "Taiwan"},
    {"code": "TZS", "name": "Tanzanian Shilling", "symbol": "TSh", "numericCode": "834", "country": "Tanzania"},
    {"code": "UAH", "name": "Ukrainian Hryvnia", "symbol": "₴", "numericCode": "980", "country": "Ukraine"},
    {"code": "UGX", "name": "Ugandan Shilling", "symbol": "USh", "numericCode": "800", "country": "Uganda"},
    {"code": "USD", "name": "United States Dollar", "symbol": "$", "numericCode": "840", "country": "United States"},
    {"code": "UYU", "name": "Uruguayan Peso", "symbol": "$U", "numericCode": "858", "country": "Uruguay"},
    {"code": "UZS", "name": "Uzbekistani Som", "symbol": "лв", "numericCode": "860", "country": "Uzbekistan"},
    {"code": "VES", "name": "Venezuelan Bolívar Soberano", "symbol": "Bs.S", "numericCode": "928", "country": "Venezuela"},
    {"code": "VND", "name": "Vietnamese Dồng", "symbol": "₫", "numericCode": "704", "country": "Vietnam"},
    {"code": "VUV", "name": "Vanuatu Vatu", "symbol": "VT", "numericCode": "548", "country": "Vanuatu"},
    {"code": "WST", "name": "Samoan Tālā", "symbol": "WS$", "numericCode": "882", "country": "Samoa"},
    {
        "code": "XAF",
        "name": "Central African CFA Franc",
        "symbol": "FCFA",
        "numericCode": "950",
        "country": ["Cameroon", "Central African Republic", "Chad", "Republic of the Congo", "Equatorial Guinea", "Gabon"],
    },
    {
        "code": "XCD",
        "name": "East Caribbean Dollar",
        "symbol": "$",
        "numericCode": "951",
        "country": ["Antigua and Barbuda", "Dominica", "Grenada", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Anguilla", "Montserrat"],
    },
    {
        "code": "XOF",
        "name": "West African CFA Franc",
        "symbol": "CFA",
        "numericCode": "952",
        "country": ["Benin", "Burkina Faso", "Guinea-Bissau", "Ivory Coast", "Mali", "Niger", "Senegal", "Togo"],
    },
    {"code": "XPF", "name": "CFP Franc", "symbol": "₣", "numericCode": "953", "country": ["French Polynesia", "New Caledonia", "Wallis and Futuna"]},
    {"code": "YER", "name": "Yemeni Rial", "symbol": "﷼", "numericCode": "886", "country": "Yemen"},
    {"code": "ZAR", "name": "South African Rand", "symbol": "R", "numericCode": "710", "country": "South Africa"},
    {"code": "ZMW", "name": "Zambian Kwacha", "symbol": "ZK", "numericCode": "967", "country": "Zambia"},
    {"code": "ZWL", "name": "Zimbabwean Dollar", "symbol": "$", "numericCode": "932", "country": "Zimbabwe"},
]

TRANSACTION_CATEGORIES = [
    "Income",
    "Transfer",
    "Food & Drink",
    "Groceries",
    "Shopping",
    "Gas & Fuel",
    "Transportation",
    "Housing",
    "Utilities",
    "Subscription",
    "Entertainment",
    "Health & Wellness",
    "Insurance",
    "Cash & ATM",
    "Fees & Charges",
    "Travel",
    "Personal Care",
    "Education",
    "Investments",
]

TRANSACTION_MERCHANTS = [
    "Starbucks",
    "Amazon",
    "Walmart",
    "Target",
    "Whole Foods Market",
    "Shell",
    "Chevron",
    "Uber",
    "Lyft",
    "Netflix",
    "Spotify",
    "Apple",
    "Costco",
    "Trader Joe's",
    "McDonald's",
    "Chipotle",
    "Home Depot",
    "Best Buy",
    "CVS Pharmacy",
    "Walgreens",
    "Delta Air Lines",
    "Airbnb",
    "PG&E",
    "Verizon Wireless",
    "24 Hour Fitness",
    "ATM Withdrawal",
    "Payroll Deposit",
    "Venmo",
    "PayPal",
    "IRS Tax Refund",
]
TRANSACTION_TYPES = ["debit", "credit"]