# Generated by Django 6.1 on 2026-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField()),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=512)),
                ("author", models.CharField(max_length=1024)),
                ("source", models.CharField(max_length=1024)),
                ("url", models.URLField()),
                ("country", models.CharField(max_length=512)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_breaking", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
